# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Factor.create([
  { :id => 2, :title => "I want to be able to live in my sandals and shorts or skirt all year round", :style => "range", :show_in_survey => true, :created_at => "2012-12-19 06:23:05", :updated_at => "2012-12-19 06:23:05" },
  { :id => 3, :title => "I prefer living the mountains over the beach or jungle", :style => "range", :show_in_survey => true, :created_at => "2012-12-19 07:01:32", :updated_at => "2012-12-19 07:01:32" },
  { :id => 4, :title => "I like mild days and cool nights", :style => "range", :show_in_survey => true, :created_at => "2012-12-19 07:01:45", :updated_at => "2012-12-19 07:01:45" },
  { :id => 5, :title => "I need to live near a major airport", :style => "range", :show_in_survey => true, :created_at => "2012-12-19 07:01:56", :updated_at => "2012-12-19 07:01:56" }
], :without_protection => true )



FactorsLocation.create([
  { :id => 1, :factor_id => 2, :location_id => 7, :value => 7, :description => "", :created_at => "2012-12-19 06:59:34", :updated_at => "2012-12-19 06:59:34" },
  { :id => 2, :factor_id => 2, :location_id => 2, :value => 4, :description => "", :created_at => "2012-12-19 07:00:18", :updated_at => "2012-12-19 07:00:18" },
  { :id => 3, :factor_id => 2, :location_id => 4, :value => 7, :description => "", :created_at => "2012-12-19 07:00:27", :updated_at => "2012-12-19 07:00:27" },
  { :id => 4, :factor_id => 2, :location_id => 3, :value => 7, :description => "", :created_at => "2012-12-19 07:00:32", :updated_at => "2012-12-19 07:00:32" },
  { :id => 5, :factor_id => 3, :location_id => 3, :value => 1, :description => "", :created_at => "2012-12-19 07:02:58", :updated_at => "2012-12-19 07:02:58" },
  { :id => 6, :factor_id => 3, :location_id => 4, :value => 1, :description => "", :created_at => "2012-12-19 07:03:07", :updated_at => "2012-12-19 07:03:07" },
  { :id => 7, :factor_id => 3, :location_id => 7, :value => 1, :description => "", :created_at => "2012-12-19 07:03:11", :updated_at => "2012-12-19 07:03:11" },
  { :id => 8, :factor_id => 3, :location_id => 2, :value => 7, :description => "", :created_at => "2012-12-19 07:03:17", :updated_at => "2012-12-19 07:03:17" },
  { :id => 9, :factor_id => 4, :location_id => 2, :value => 7, :description => "", :created_at => "2012-12-19 07:03:23", :updated_at => "2012-12-19 07:03:23" },
  { :id => 10, :factor_id => 4, :location_id => 7, :value => 4, :description => "", :created_at => "2012-12-19 07:03:35", :updated_at => "2012-12-19 07:03:35" },
  { :id => 11, :factor_id => 4, :location_id => 4, :value => 4, :description => "", :created_at => "2012-12-19 07:03:39", :updated_at => "2012-12-19 07:03:39" },
  { :id => 12, :factor_id => 4, :location_id => 3, :value => 4, :description => "", :created_at => "2012-12-19 07:03:44", :updated_at => "2012-12-19 07:03:44" },
  { :id => 13, :factor_id => 5, :location_id => 3, :value => 4, :description => "", :created_at => "2012-12-19 07:04:05", :updated_at => "2012-12-19 07:04:05" },
  { :id => 14, :factor_id => 5, :location_id => 4, :value => 6, :description => "", :created_at => "2012-12-19 07:04:12", :updated_at => "2012-12-19 07:04:12" },
  { :id => 15, :factor_id => 5, :location_id => 7, :value => 3, :description => "", :created_at => "2012-12-19 07:04:24", :updated_at => "2012-12-19 07:04:24" },
  { :id => 16, :factor_id => 5, :location_id => 2, :value => 5, :description => "", :created_at => "2012-12-19 07:04:31", :updated_at => "2012-12-19 07:04:31" }
], :without_protection => true )



FactorsUser.create([
  { :id => 1, :factor_id => 3, :user_id => 1, :value => 6, :description => "", :created_at => "2012-12-19 08:10:10", :updated_at => "2012-12-19 08:10:10" },
  { :id => 2, :factor_id => 4, :user_id => 1, :value => 2, :description => "", :created_at => "2012-12-19 08:10:15", :updated_at => "2012-12-19 08:10:15" },
  { :id => 3, :factor_id => 5, :user_id => 1, :value => 8, :description => "", :created_at => "2012-12-19 08:11:07", :updated_at => "2012-12-19 08:11:07" }
], :without_protection => true )



Location.create([
  { :id => 3, :title => "Lomas del Olon", :short_desc => "", :long_desc => "", :city => "", :region => "", :country => "", :geography => "", :population => "", :image_1 => "", :image_2 => "", :created_at => "2012-12-18 17:46:01", :updated_at => "2012-12-18 17:46:01", :activities => nil, :distance_to_hospital => nil, :distance_to_airport => nil, :internet_speed => nil, :climate => nil, :amenities => nil, :expat_population => nil, :health_care => nil, :distance_to_international_school => nil, :kids_friendliness => nil, :quaintness => nil, :interesting_activities_events => nil, :liberal_or_conservative => nil, :same_sex_friendly => nil, :religions => nil, :nightlife => nil, :distance_to_nightlife => nil, :nightlife_index => nil, :province => nil, :elevation => nil, :distance_to_city => nil },
  { :id => 4, :title => "Manta", :short_desc => "", :long_desc => "", :city => "", :region => "", :country => "", :geography => "", :population => "", :image_1 => "", :image_2 => "", :created_at => "2012-12-18 17:50:19", :updated_at => "2012-12-18 17:50:19", :activities => nil, :distance_to_hospital => nil, :distance_to_airport => nil, :internet_speed => nil, :climate => nil, :amenities => nil, :expat_population => nil, :health_care => nil, :distance_to_international_school => nil, :kids_friendliness => nil, :quaintness => nil, :interesting_activities_events => nil, :liberal_or_conservative => nil, :same_sex_friendly => nil, :religions => nil, :nightlife => nil, :distance_to_nightlife => nil, :nightlife_index => nil, :province => nil, :elevation => nil, :distance_to_city => nil },
  { :id => 7, :title => "Bahia de Caraquez", :short_desc => "", :long_desc => "", :city => "Bahia de Caraquez", :region => "Coast", :country => nil, :geography => nil, :population => "19,703", :image_1 => "", :image_2 => "", :created_at => "2012-12-19 05:29:08", :updated_at => "2012-12-19 05:29:18", :activities => "Surfing, Yoga", :distance_to_hospital => "", :distance_to_airport => "2.5 hours to Manta", :internet_speed => "", :climate => "arid", :amenities => "No grocery store", :expat_population => "", :health_care => "There are hospitals in Pederanales and Bahia De Caraquez that are well equipped. Emergency care (as in paramedic response) is available in Bahia. Also, there is a private clinic in Bahia that is fairly well equipped.", :distance_to_international_school => "", :kids_friendliness => "", :quaintness => "", :interesting_activities_events => "eco friendly city", :liberal_or_conservative => "", :same_sex_friendly => "", :religions => "", :nightlife => "Nightlife here is low-key—there’s only one disco in town, Dabei (Malecón, 8 p.m.–2 a.m. Fri.–Sat., $5) on the north side of the malecón in the Yacht Club. Alternately, head to nearby Canoa on weekends", :distance_to_nightlife => "45 min to Canoa", :nightlife_index => 3, :province => "Manabi", :elevation => "0", :distance_to_city => "6 hours to Guay" },
  { :id => 2, :title => "Chordeleg", :short_desc => "", :long_desc => "", :city => "Chordeleg", :region => "", :country => "", :geography => "", :population => "5,500", :image_1 => "", :image_2 => "", :created_at => "2012-12-18 17:45:48", :updated_at => "2012-12-19 05:31:40", :activities => "", :distance_to_hospital => "", :distance_to_airport => "1 hour to Cuenca", :internet_speed => "", :climate => "subtropical highland", :amenities => "", :expat_population => "", :health_care => "", :distance_to_international_school => "", :kids_friendliness => "", :quaintness => "", :interesting_activities_events => "", :liberal_or_conservative => "", :same_sex_friendly => "", :religions => "", :nightlife => "Not much I think", :distance_to_nightlife => "1 hour to Cuenca", :nightlife_index => 2, :province => "Azuay", :elevation => "", :distance_to_city => "4 hours to Guay" }
], :without_protection => true )



Page.create([
  { :id => 1, :title => "Home", :top_nav_links => "<a href=\"/pages/1\">Home</a> <a href=\"/pages/2\">About Us</a> <a href=\"/pages/3\">Consulting Services</a> <a href=\"/pages/4\">Global Research</a>  <ahref=\"/pages/5\">Contact Us</a>", :main_area_1 => "Find the Perfect location for you", :main_area_2 => "<a href=\"locations/1\"><img src=\"http://internationalliving.com/wp-content/blogs.dir/1/files/2010/04/cuenca-ecuador3-300x198.jpg\"></a>", :main_area_3 => "", :side_area_1 => "Top 10 Best Locations of 2012", :side_area_2 => "Get New Listing info here & What is happening in BELIZE now !\r\n<form>\r\n<input type=text name=email>\r\n<input type=submit value=\"Join\">\r\n</form>", :side_area_3 => "What You Need to Know Before You Buy", :template => "", :created_at => "2012-11-03 19:44:03", :updated_at => "2012-11-03 20:01:31" }
], :without_protection => true )



SiteConfig.create([
  { :id => 1, :title => "Offshore Real Estate International (OREI)", :desc => "Offshore Real Estate International is managed by Bill Scuba.", :logo => "logo.png", :contact_us_blurb => "Contact Us\r\nUSA +1 858 353 4814\r\n<a href=\"mailto:info@offshorerei.com\">info@offshorerei.com</a>", :created_at => "2012-11-03 19:40:15", :updated_at => "2012-11-03 19:57:42", :top_nav_links => nil, :footer_links => nil }
], :without_protection => true )



User.create([
  { :id => 1, :email => "bergen@bergenmoore.com", :first_name => "Bergen", :last_name => "Moore", :created_at => "2012-12-19 07:46:21", :updated_at => "2012-12-19 07:46:21" }
], :without_protection => true )


