# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Location.create([
  { :id => 1, :title => "Bahia de Caraquez", :short_desc => "", :long_desc => "", :city => "", :region => "", :country => "", :geography => "", :population => "", :image_1 => "", :image_2 => "", :created_at => "2012-12-18 17:45:37", :updated_at => "2012-12-18 17:45:37" },
  { :id => 2, :title => "Canoa", :short_desc => "", :long_desc => "", :city => "", :region => "", :country => "", :geography => "", :population => "", :image_1 => "", :image_2 => "", :created_at => "2012-12-18 17:45:48", :updated_at => "2012-12-18 17:45:48" },
  { :id => 3, :title => "Lomas del Olon", :short_desc => "", :long_desc => "", :city => "", :region => "", :country => "", :geography => "", :population => "", :image_1 => "", :image_2 => "", :created_at => "2012-12-18 17:46:01", :updated_at => "2012-12-18 17:46:01" },
  { :id => 4, :title => "Manta", :short_desc => "", :long_desc => "", :city => "", :region => "", :country => "", :geography => "", :population => "", :image_1 => "", :image_2 => "", :created_at => "2012-12-18 17:50:19", :updated_at => "2012-12-18 17:50:19" }
], :without_protection => true )



LocationsQuestion.create([
  { :id => 1, :location_id => 1, :question_id => 1, :value => 7, :created_at => "2012-12-18 17:47:54", :updated_at => "2012-12-18 17:47:54" },
  { :id => 2, :location_id => 1, :question_id => 2, :value => 1, :created_at => "2012-12-18 17:48:49", :updated_at => "2012-12-18 17:48:49" },
  { :id => 3, :location_id => 1, :question_id => 3, :value => 4, :created_at => "2012-12-18 17:48:56", :updated_at => "2012-12-18 17:48:56" },
  { :id => 4, :location_id => 2, :question_id => 1, :value => 7, :created_at => "2012-12-18 17:49:11", :updated_at => "2012-12-18 17:49:11" },
  { :id => 5, :location_id => 2, :question_id => 2, :value => 1, :created_at => "2012-12-18 17:49:15", :updated_at => "2012-12-18 17:49:15" },
  { :id => 6, :location_id => 2, :question_id => 3, :value => 4, :created_at => "2012-12-18 17:49:30", :updated_at => "2012-12-18 17:49:30" },
  { :id => 7, :location_id => 3, :question_id => 1, :value => 7, :created_at => "2012-12-18 17:49:38", :updated_at => "2012-12-18 17:49:38" },
  { :id => 8, :location_id => 3, :question_id => 2, :value => 1, :created_at => "2012-12-18 17:49:46", :updated_at => "2012-12-18 17:49:46" },
  { :id => 9, :location_id => 3, :question_id => 3, :value => 4, :created_at => "2012-12-18 17:49:57", :updated_at => "2012-12-18 17:49:57" },
  { :id => 10, :location_id => 4, :question_id => 1, :value => 7, :created_at => "2012-12-18 17:51:26", :updated_at => "2012-12-18 17:51:26" },
  { :id => 11, :location_id => 4, :question_id => 2, :value => 1, :created_at => "2012-12-18 17:51:30", :updated_at => "2012-12-18 17:51:30" },
  { :id => 12, :location_id => 4, :question_id => 3, :value => 4, :created_at => "2012-12-18 17:51:38", :updated_at => "2012-12-18 17:51:38" },
  { :id => 13, :location_id => 1, :question_id => 4, :value => 3, :created_at => "2012-12-18 17:51:48", :updated_at => "2012-12-18 17:51:48" },
  { :id => 14, :location_id => 2, :question_id => 4, :value => 3, :created_at => "2012-12-18 17:51:52", :updated_at => "2012-12-18 17:51:52" },
  { :id => 15, :location_id => 3, :question_id => 4, :value => 4, :created_at => "2012-12-18 17:52:02", :updated_at => "2012-12-18 17:52:02" },
  { :id => 16, :location_id => 4, :question_id => 4, :value => 6, :created_at => "2012-12-18 17:52:13", :updated_at => "2012-12-18 17:52:13" }
], :without_protection => true )



Page.create([
  { :id => 1, :title => "Home", :top_nav_links => "<a href=\"/pages/1\">Home</a> <a href=\"/pages/2\">About Us</a> <a href=\"/pages/3\">Consulting Services</a> <a href=\"/pages/4\">Global Research</a>  <ahref=\"/pages/5\">Contact Us</a>", :main_area_1 => "Find the Perfect location for you", :main_area_2 => "<a href=\"locations/1\"><img src=\"http://internationalliving.com/wp-content/blogs.dir/1/files/2010/04/cuenca-ecuador3-300x198.jpg\"></a>", :main_area_3 => "", :side_area_1 => "Top 10 Best Locations of 2012", :side_area_2 => "Get New Listing info here & What is happening in BELIZE now !\r\n<form>\r\n<input type=text name=email>\r\n<input type=submit value=\"Join\">\r\n</form>", :side_area_3 => "What You Need to Know Before You Buy", :template => "", :created_at => "2012-11-03 19:44:03", :updated_at => "2012-11-03 20:01:31" }
], :without_protection => true )



Question.create([
  { :id => 1, :title => "I want to be able to live in my sandals and shorts or skirt all year round", :subtitle => "", :option_label => "", :option_value => "", :style => "", :created_at => "2012-12-18 17:46:25", :updated_at => "2012-12-18 17:46:25" },
  { :id => 2, :title => "I prefer living the mountains over the beach or jungle", :subtitle => "", :option_label => "", :option_value => "", :style => "", :created_at => "2012-12-18 17:46:47", :updated_at => "2012-12-18 17:46:47" },
  { :id => 3, :title => "I like mild days and cool nights", :subtitle => "", :option_label => "", :option_value => "", :style => "", :created_at => "2012-12-18 17:47:01", :updated_at => "2012-12-18 17:47:01" },
  { :id => 4, :title => "I need to live near a major airport", :subtitle => "", :option_label => "", :option_value => "", :style => "", :created_at => "2012-12-18 17:51:14", :updated_at => "2012-12-18 17:51:14" }
], :without_protection => true )



SiteConfig.create([
  { :id => 1, :title => "Offshore Real Estate International (OREI)", :desc => "Offshore Real Estate International is managed by Bill Scuba.", :logo => "logo.png", :contact_us_blurb => "Contact Us\r\nUSA +1 858 353 4814\r\n<a href=\"mailto:info@offshorerei.com\">info@offshorerei.com</a>", :created_at => "2012-11-03 19:40:15", :updated_at => "2012-11-03 19:57:42", :top_nav_links => nil, :footer_links => nil }
], :without_protection => true )


